### ISSUE TITLE
[Servidor] Documentar comunicação app-servidor (WEB services)

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/server#5]

**Comment by fpcardoso** [comment]
Documentação da API REST encontra-se em [API REST](https://github.com/best-software-company/docs/blob/master/markdown/API-Web-Service.md)

**Comment by fpcardoso** [comment]
Documentação da API REST revisada e encontra-se em [DOC API REST](https://github.com/best-software-company/docs/blob/master/markdown/API-Web-Service.md)
