### ISSUE TITLE
[Servidor] Criar diagrama de classes do Servidor.

### ISSUE THREAD

**Issue by fpcardoso** [best-software-company/server#6]
Nessa tarefa iremos criar o diagrama de classes do web service. Sugestão de utilizar a ferramenta Astah para criação, pois a mesma converte o diagrama em arquivos.

**Comment by luizaalves** [comment]
[Diagrama de classes do servidor](https://github.com/best-software-company/docs/blob/master/markdown/Diagrama-de-Classes-Servidor.md)
